### ISSUE TITLE
Repository offline

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#15]
Hi Pierre-Yves,

It's been a while, I think the repo : http://repo1.nuxsfm.org/nuxsfm/os/$arch is offline.
Do you want me to create a mirror for it on one of my server ?

Best regards,

Stephane

**Comment by pyp22** [comment]
erf still offline ? My IRL old friend recently made some changes on his Cloud Computing Center. I have to check that with him. 

If you have the availability to do so, yes please. I could CNAME to one of your IP in Gandi DNS records or directly your FQDN. Thanks a lot Stéphane!

**Comment by pyp22** [comment]
main repo working for me. I changed Gandi's DNS but TTL is 3 hours. But i think a repo2 pointing to your own server is very good idea & opportunity ^^ A big thanks!

**Comment by stephane-lb** [comment]
Ok, I am going to do that tonight. Any information on how to build the repo from git ?

**Comment by pyp22** [comment]
For repo1.nuxsfm.org (built binaries) i suggest you a rsync over a crontab during the night. From git, hmmm ... Might be a bit more tricky ^^ a PY script maybe ?

**Comment by stephane-lb** [comment]
Yeah was thinking about a py-script or a hook...  I will take a day or two to think of the best way. 

Not sure I know the rsync command, could you be more specific please ?

Have a great week-end !

**Comment by pyp22** [comment]
powerful tool to copy & sync files. https://en.wikipedia.org/wiki/Rsync
pacman -Sy rsync ;)

**Comment by stephane-lb** [comment]
Hi Pierre-Yves,

So a little update, that's the script that I am trying to use, and at the moment it is not working... If with your experience you could look at and told to me what I am doing wrong it would be fantastic.

Thanks,

Stéphane

```bash
#!/bin/bash

# Configuration
SOURCE='rsync://repo1.nuxsfm.org'
DEST='/www/repo/'
BW_LIMIT='500'
REPOS='nuxsfm'
RSYNC_OPTS="-rtlHq --delete-after --delay-updates --copy-links --safe-links --max-delete=1000 --bwlimit=${BW_LIMIT} --delete-excluded --exclude=.*"
LCK_FLE='/tmp/nuxsfm-sync.lck'

PATH='/usr/bin'

# Make sure only 1 instance runs
if [ -e "$LCK_FLE" ] ; then
	OTHER_PID=$(cat $LCK_FLE)
	echo "Another instance already running: $OTHER_PID"
	exit 1
fi
echo $$ > "$LCK_FLE"

for REPO in $REPOS ; do
	echo "Syncing $REPO"
	rsync $RSYNC_OPTS ${SOURCE}/${REPO} ${DEST}
done

# Cleanup
rm -f "$LCK_FLE"

exit 0
```

**Comment by pyp22** [comment]
Hi Stéphane, ok. NP i'll take a look at it this WE. 
Best regards,
PY

**Comment by pyp22** [comment]
Hi Stéphane,
Normal that it does not work, you need a ssh access to do it. I'm going to create a user on the server. But first send a private mail (nuxsfm@gmail.com) with 2 ssl pub keys (rsa & dsa) see https://wiki.archlinux.org/index.php/SSH_keys if you're not familiar with that.

Some pages that might help you on rsync: http://joelinoff.com/blog/?p=941 Exaclty what you need to set up a synced mirror.

Best regards,

PY

**Comment by stephane-lb** [comment]
Hi Pierre-Yves,

That's what I supposed, and I was not really sure.
Just sent to you my pub key.

Have a fantastic day,

Stephane

**Comment by stephane-lb** [comment]
I am auto answering, so the repo is :

```
[nuxsfm]
SigLevel = Never
Server = Server = http://repo1.nuxsfm.org/2015.12.01/os/$arch
```

Thanks for your help Pierre Yves
