### ISSUE TITLE
Loop in dependencies [ ceres / eigen / openMVS ]

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#16]
Hi Pierre-Yves,

I was recompiling openMVS, so there is a small issue :
```
- ceres-solver depends of eigen-nuxsfm
- openMVS depends of eigen
- eigen and eigen-nuxsfm are in conflict
```
However I might say something wrong because not sure my Arch is really clean at the moment.

Have a good day,

Stephane

**Comment by stephane-lb** [comment]
Hum, a little bit more info, by trying to installing ceres using the makepkg -s -i, I got : 
```
-- Removed runtime path from "/home/johndoe/NuxSFM-2.0/stable/scientifics/ceres-solver/pkg/ceres-solver-nuxsfm/usr/local/lib/libceres.so.1.12.0"
rm: cannot remove ‘/home/johndoe/NuxSFM-2.0/stable/scientifics/ceres-solver/pkg/ceres-solver-nuxsfm/usr/local/share’: No such file or directory
```

Hope you will have an idea...

**Comment by pyp22** [comment]
Hi Stéphane,

Ok thanks. I'll check that on a fresh VM.

By the way, use openMVS-v0.5 (default from git/stable). I switched v0.6 to
testing. Its completely unstable. Seg fault on all binaries. Same thing on
Linux Mint i use to check dependencies. Got to see that with Pierre &
Cdcseave.

2016-02-19 12:48 GMT+01:00 stephane-lb <notifications@github.com>:

> Hum, a little bit more info, by trying to installing ceres using the
> makepkg -s -i, I got :
>
> -- Removed runtime path from "/home/johndoe/NuxSFM-2.0/stable/scientifics/ceres-solver/pkg/ceres-solver-nuxsfm/usr/local/lib/libceres.so.1.12.0"
> rm: cannot remove ‘/home/johndoe/NuxSFM-2.0/stable/scientifics/ceres-solver/pkg/ceres-solver-nuxsfm/usr/local/share’: No such file or directory
>
> Hope you will have an idea...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyp22/NuxSFM-2.0/issues/16#issuecomment-186184466>.
>



-- 
Bien cordialement,
Best regards,

PY
