### ISSUE TITLE
pMVS : Compilation issue

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#18]
Hi Pierre-Yves,

A note about a small issue during the compilation of pMVS : 
<img width="641" alt="screen shot 2016-03-05 at 11 29 22" src="https://cloud.githubusercontent.com/assets/5918598/13547335/beeefb52-e2c6-11e5-95a4-0cdff620f0f8.png">

I will investigate these errors later, however if you have time and have an idea ... ;-)

Have a great day

Stephane

**Comment by pyp22** [comment]
Strange ... That might occurs sometime when a git repo is beeing update or modified. As pmvs one is not updated anymore, this should not happen. I ran for a try here. No pb. Did you try deleting your local sources (the whole dir) & rerun makepkg ?

**Comment by stephane-lb** [comment]
Hi Pierre-Yves,

I think I found it, not fixed it yet, and that's the issue : 
![screen shot 2016-03-09 at 17 27 36](https://cloud.githubusercontent.com/assets/5918598/13644179/60b328b6-e61c-11e5-872b-5624c290c5b3.png)

Hope that will help,

Stephane

**Comment by stephane-lb** [comment]
Hi Pierre-Yves,

I just removed the function pkgver() and it works. So I think that will be the best way to do.

Have a good day,

Stephane

**Comment by pyp22** [comment]
Hi Stéphane. Thanks. I don't know why this occure sometimes. Latest compilation versionning got ok. Maybe a github trick ? Anyway ok let's get rid of this. Pulling new script.

**Comment by stephane-lb** [comment]
Hi, i think it depends if you tag your commit or not. I will read the doc and let you know asap.

Have a good day,

Stephane

**Comment by stephane-lb** [comment]
Thanks Pierre Yves.
