### ISSUE TITLE
Issue with gsl

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#3]
Hi Pierre Yves,

Sorry for this third bug report,  A new one, I was trying to compile pmvs, so I had to compile gsl-nuxsfm.
But I just got an error at the end of the installation.

```
error: failed to commit transaction (conflicting files)
gsl-nuxsfm: /usr/local/share/man exists in filesystem
Errors occurred, no packages were upgraded.
==> WARNING: Failed to install built package(s).
```

I am thinking to fork the repo and do part of the work, in all cases thanks for your work and your youtube channel. It is amazing.

Kenavo ;-)

Stephane

**Comment by pyp22** [comment]
This a native pb with the symlink of man in /usr/local/share/man. Seeing how to solv it. Meanwhile a rm /usr/local/share/man then reinstall package will temporary solve that.
Feel free to fork and make some pull requests i could integrate on main repo :) 
I'm preparing a large collection of new scripts i'll push in a few days if i have enough free time ;-)

Kenavo :)

PY

**Comment by stephane-lb** [comment]
I just applied what you said and it fixed the issue.

Thanks,

Stéphane

**Comment by pyp22** [comment]
Pb identified. Pacmabn is not able to follow symlink in /usr/local/share/man. Arch doc is not really clear on the origin of the pb. As it is not a broken pacman database (monitored files by it) and as i don't want to use the pacmam -S --ignore-filesystem and solution is to get around it by adding a  --mandir=/usr/local/share in the configure. See commit https://github.com/pyp22/NuxSFM-2.0/commit/2dc2eb3b5c08230c1062e9f8699c7c32613061b2.
