### ISSUE TITLE
Troubles with libsiftgpu

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#5]
Hi Pierre Yves, 

A new one for the collection, it is kind of the same issue reported previously between openMVG and openMVG-qt :

```
error: failed to commit transaction (conflicting files)
/usr/local/bin/MultiThreadSIFT exists in both 'libsiftgpu-CUDA' and 'libsiftgpu-MESA'
/usr/local/bin/SimpleSIFT exists in both 'libsiftgpu-CUDA' and 'libsiftgpu-MESA'
/usr/local/bin/TestWinGlut exists in both 'libsiftgpu-CUDA' and 'libsiftgpu-MESA'
/usr/local/bin/speed exists in both 'libsiftgpu-CUDA' and 'libsiftgpu-MESA'
/usr/local/lib/libsiftgpu.so exists in both 'libsiftgpu-CUDA' and 'libsiftgpu-MESA'
Errors occurred, no packages were upgraded.
==> WARNING: Failed to install built package(s).
```

Good night,

Stephane

**Comment by pyp22** [comment]
Hi Stephane, thanks a lot for your feedbacks. 

Due to the lack of conflicts=(libsiftgpu sift) in both fonctions of the script. Solved by commit https://github.com/pyp22/NuxSFM-2.0/commit/7a8349fa14267d9d5fd82864c95d1052077e265a

PY

**Comment by stephane-lb** [comment]
Hi Pierre Yves, 

That's really strange, since the last commit I got this one :+1: 
```
g++ -o build/CuTexImage.o src/SiftGPU/CuTexImage.cpp -Iinclude -fPIC -L/usr/lib64 -L/usr/lib -L./bin -L./lib -Wall -Wno-deprecated -pthread   -march=native -mfpmath=sse -DCUDA_SIFTGPU_ENABLED -I/usr/local/cuda/include -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -c 
src/SiftGPU/CuTexImage.cpp:33:18: fatal error: cuda.h: No such file or directory
```
Which is completely normal because Cuda is in /opt/cuda ... 
But you seems make the test in your makefile, did I miss something ?

Thanks for your help,

Stephane

**Comment by pyp22** [comment]
Hi Stephane,

Strange ... i can't reproduce that here. Can you try with make -j1 CUDA_INSTALL_PATH=/opt/cuda in package_libsiftgpu-CUDA() instead of a simple make -j1 ?

Thx,

PY

**Comment by stephane-lb** [comment]
Hi Pierre Yves,

Just tested and unfortunately nothing changed. I will try to investigate more, later tonight,

Thank you very much for your help,

Stephane

**Comment by stephane-lb** [comment]
Hi Pierre Yves,

So the error is line 17 in the makefile.noncuda . I replace the path with /opt/cuda and everything is now working well.

Thanks for your help,

Stephane

**Comment by pyp22** [comment]
Understood why. It detects presence of Cuda and put siftgpu_enable_cuda to 1. Let's force to siftgpu_enable_cuda = 0

**Comment by stephane-lb** [comment]
got a similar issue with pba too.

**Comment by pyp22** [comment]
Can you link the compilation fail pse ?

**Comment by stephane-lb** [comment]
I will reproduce it asap ( I solve it with paceman -U pba-cuda ), sorry it is on an other computer.

**Comment by pyp22** [comment]
Tnanks :)

Strange. This should not occure as conflicting & replaces routines are well defined in script. Are you using the single pacman -U command ? I mean without any other option ? It should normally give this:

:: pba-CUDA and pba-non-CUDA are in conflict (pba). Remove pba-non-CUDA? [y/N]

By the way a short explanation of CUDA and non-CUDA splitting packages. If you run virtualize or native without Nvidia card, CUDA packages are not required and you may prefer to use non CUDA (Mesa).

Regards,

PY

**Comment by stephane-lb** [comment]
Well not exactly, I used:
```
 pacman -U pba-CUDA
```
For my understanding it was a way to choose one of the 2 packages.
Hope that help,.

Cheers,

**Comment by pyp22** [comment]
Correct. 
xxx-CUDA-xxx package have to be used when running native AND Nvidia card,
xxx-non-CUDA-xxx have to be use for VM OR native with non Nvidia Card (Mesa).

Regards

PY

**Comment by stephane-lb** [comment]
Ok,  my mistake, I did that wrong. ( I was using cuda version in my VM )

Cheers,

Stéphane

**Comment by pyp22** [comment]
Corrected with las commits.
