### ISSUE TITLE
OpenMVG : Version ?

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#7]
Hi Pierre Yves,

I was reading some of the news about OpenMVG and Pierre just released a V1, I was thinking to update the package build of the v0.9, but it looks like it is directly linked to the git repository. Could you confirm that please ?

Have a lovely week-end and see you Monday,

Stéphane

**Comment by pyp22** [comment]
It's a WIP initiated by @pmoulon. See https://github.com/openMVG/openMVG/issues/438
