### ISSUE TITLE
Builders script

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#9]
Hi Pierre Yves,

It is been a while, and I thank you for your recent work.
I just re-installed a VM and clone the repo, then I launch the builder.sh in stable/scientific : 
```
[saorel@bluestar scientifics]$ ./Builder.sh 
ceres-solver
PKGBUILD
Building---> ceres-solver
==> Making package: ceres-solver 1.11.0.r4.g7efc92d-1 (Mon 21 Dec 17:01:44 GMT 2015)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> eigen>=3.1.0
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> eigen>=3.1.0
  -> metis
  -> suitesparse
==> ERROR: Could not resolve all dependencies.
```

For my point of view the error is due to the order of the packages in this variable : 
```
list=(ceres-solver eigen flann gsl metis mosek)
```
I think it should be better to start with eigen.(and metis) ;-) 

I made the change, but have to install fakeroot before to go further ( and I just launch an update )

Have a good evening,

Stephane

P.S : just got an issue with that : 
```
        # Change to suit your needs
        sudo scp ${packages} voyager:/srv/http/2015.06.01/nuxsfm/os/x86_64
```
So I suppose that the builder script is only for you ;-)

**Comment by pyp22** [comment]
that's a really beta script. Works only for me by now. See top of it. But tnx for suggestion.
